In [106]:
import numpy as np
import torch
import  pdb

In [136]:
dim=3

#mymat = torch.tensor(np.random.uniform(size=(dim, dim))).float()
mymat = torch.tensor(np.random.normal(size=(dim, dim))).float()







In [137]:
def specnorm0(weightmat, repeat=3): 
    mydim0 = weightmat.shape[0]
    mydim1 = weightmat.shape[1]

    print(mydim0, mydim1)
    random_vec_r = torch.tensor(np.random.uniform(size=(mydim1,1))).float()
    random_vec_l = torch.tensor(np.random.uniform(size=(1, mydim0))).float() 

    
    for k in range(repeat):
        random_vec_r = weightmat @ random_vec_r 
        random_vec_r = random_vec_r / torch.sqrt(torch.sum(random_vec_r**2))
        
        random_vec_l = random_vec_l @ weightmat
        random_vec_l = random_vec_l / torch.sqrt(torch.sum(random_vec_l**2))

    print( (weightmat @ random_vec_r )/ random_vec_r)
    print( (random_vec_l @ weightmat) / random_vec_l)
    
    print('val')
    print( random_vec_l @ weightmat @ random_vec_r)

    print("eigen")
    print( torch.real(torch.linalg.eig(weightmat).eigenvalues))
    print("SVD")
    print( torch.linalg.svd(weightmat).S)

    return random_vec_l, random_vec_r


    
    
def specnorm1(weightmat, repeat=3): 
    mydim0 = weightmat.shape[0]
    mydim1 = weightmat.shape[1]

    random_vec_r = torch.tensor(np.random.uniform(size=(mydim1,1))).float()
    random_vec_l = torch.tensor(np.random.uniform(size=(mydim0,1))).float() 

    for k in range(repeat):
        random_vec_l = weightmat @ random_vec_r 
        random_vec_l = random_vec_l / torch.sqrt(torch.sum(random_vec_l**2))
        
        random_vec_r = weightmat.permute([1,0]) @ random_vec_l
        random_vec_r = random_vec_r / torch.sqrt(torch.sum(random_vec_r**2))

    val = random_vec_l.permute([1,0]) @ weightmat @ random_vec_r
    #print( (weightmat @ random_vec_r )/ random_vec_r)
    #print( (weightmat.permute([1,0]) @ random_vec_l ) / random_vec_l)
    print('val')
    print(val)
    #print( torch.real(torch.linalg.eig(weightmat).eigenvalues))
    print('SVD')
    print( torch.linalg.svd(weightmat).S)


        
    return val



specnorm0(mymat, repeat=10)


specnorm1(mymat, repeat=3)



3 3
tensor([[ 0.1365],
        [-0.7177],
        [-0.5243]])
tensor([[ 2.1218, -0.4689,  0.1254]])
val
tensor([[0.4847]])
eigen
tensor([-0.7279, -0.7279,  1.1955])
SVD
tensor([2.4336, 1.2185, 0.4744])
val
tensor([[2.4328]])
SVD
tensor([2.4336, 1.2185, 0.4744])


tensor([[2.4328]])

In [138]:
mymat_symm = mymat + mymat.permute([1,0])
specnorm0(mymat_symm, repeat=3)


specnorm1(mymat_symm, repeat=3)

3 3
tensor([[-3.2025],
        [ 5.1467],
        [-7.4352]])
tensor([[  -2.9271, -147.9742,   26.1514]])
val
tensor([[3.0852]])
eigen
tensor([-3.4056,  2.4159,  0.4691])
SVD
tensor([3.4056, 2.4159, 0.4691])
val
tensor([[3.4023]])
SVD
tensor([3.4056, 2.4159, 0.4691])


tensor([[3.4023]])

In [143]:
yourmat = torch.tensor(np.random.normal(size=(dim, dim*2))).float()



In [146]:
specnorm1(yourmat, repeat=10)

val
tensor([[3.2715]])
SVD
tensor([3.2715, 1.9810, 1.3413])


tensor([[3.2715]])