In [1]:
#pip install scikit-image
#pip install opencv-python
#pip install einops
import sys
sys.path.append('../')
sys.path.append('../datasets')


import yaml
from torch.utils.data import DataLoader
from datasets.seq_mnist import SequentialMNIST
from datasets import seq_mnist 



from source import yaml_utils as yu

#config_path = '../configs/mnist/lstsq/lstsq.yml'
config_path = '../configs/mnist/lstsq/lstsq.yml'



with open(config_path, 'r') as f:
    config = yaml.safe_load(f)
    
data = yu.load_component(config['train_data'])

train_loader = DataLoader(data, batch_size=config['batchsize'], shuffle=True, num_workers=config['num_workers'])

/usr/local/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [2]:
next(iter(train_loader))

[tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],
 
          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],
 
          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]]],
 
 
         [[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0

In [36]:
train_loader.dataset[0]

[tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],
 
         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],
 
         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]),
 tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
       

In [29]:
import math
import colorsys

data.init_shared_transition_parameters()
(angles_v, angles_a) = (data.angles_v, data.angles_a)
(color_v, color_a) = (data.color_v, data.color_a)
(pos_v, pos_a) = (data.pos_v, data.pos_a)
color_0 = data.rng.uniform(0, 1, size=1)

t = 1

print(color_a)
print(color_t)
print(color_v)

color_t = (0.5 * color_a * t**2 + t * color_v + color_0) % 1
print(color_t)
print(colorsys.hsv_to_rgb(color_t[0], 1., 1.))



[0.]
[0.24475886]
[0.23951142]
[0.90886729]
(1.0, 0.0, 0.5467962523076002)


(0.0, 1, array([0.08790063]))


In [52]:
colorvals = colorsys.hsv_to_rgb(color_t, 1, 1)
colorvals = [colorvals[0], colorvals[1], colorvals[-1][0] ]
np.asarray(colorvals, dtype=np.float32)

array([0.        , 1.        , 0.48706248], dtype=float32)

In [53]:
rgb

array([0.        , 1.        , 0.48706248], dtype=float32)